# Local Production - My PC

GET http://localhost:8080/contacts HTTP/1.1

###
GET http://localhost:8080/contacts/6272a7f1e14ad42927f1df14 HTTP/1.1

###
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Fabrice",
        "lastName": "Banyingela",
        "email": "tshiyoyi@gmail.com",
        "favoriteColor": "blue",
        "birthday": "October 14, 1980"
    }

###
PUT http://localhost:8080/contacts/6272a7f1e14ad42927f1df14 HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Fabrice",
        "lastName": "Banyingela",
        "email": "tshiyoyi@gmail.com",
        "favoriteColor": "green",
        "birthday": "October 14, 1980"
    }

###
DELETE http://localhost:8080/contacts/6272a5e9e14ad42927f1df12 HTTP/1.1

###

# Server Production - Heroku

GET https://cse341-fab-project.herokuapp.com/contacts HTTP/1.1

###
GET https://cse341-fab-project.herokuapp.com/contacts/626fea9eef09ea629d49bba2 HTTP/1.1

###
POST https://cse341-fab-project.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Alain",
        "lastName": "Ngandu",
        "email": "alino@gmail.com",
        "favoriteColor": "blue",
        "birthday": "May 20, 1986"
    }

###
PUT https://cse341-fab-project.herokuapp.com/contacts/626fea9eef09ea629d49bba1 HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Daniel",
        "lastName": "Nimi",
        "email": "daniel@byui.edu",
        "favoriteColor": "yellow",
        "birthday": "August 13, 1989"
    }

###
DELETE https://cse341-fab-project.herokuapp.com/contacts/6272936bbdaa5f6c18b46bd3 HTTP/1.1